var Constants = (function(){
	'use strict';

	return {
		IS_MIR: true,
		VERSION: '0.1.0',
		NODE_ADDRESS: 'https://node.mir.dei.su',
		MATCHER_ADDRESS: 'https://m.mir.dei.su',
		SUPPORT_LINK: 'dei.su',

		/* network */
		ADDRESS_VERSION: 1,
		NETWORK_CODE: 'S',
		NETWORK_NAME: 'mirnet',
		INITIAL_NONCE: 0,

		/* address */
		RAW_ADDRESS_LENGTH : 35,
		ADDRESS_PREFIX: '1S', // '1W',
		MAINNET_ADDRESS_REGEXP: /^[a-zA-Z0-9]{35}$/,

		/* features */
		ALIAS_VERSION: 2,

		/* ui */
		MINIMUM_PAYMENT_AMOUNT : 1e-8,
		MINIMUM_TRANSACTION_FEE : 0.001,
		AMOUNT_DECIMAL_PLACES : 8,
		JAVA_MAX_LONG: 9223372036854775807,
		MAXIMUM_ATTACHMENT_BYTE_SIZE: 140,

		/* transactions */
		PAYMENT_TRANSACTION_TYPE : 2,
		ASSET_ISSUE_TRANSACTION_TYPE: 3,
		ASSET_TRANSFER_TRANSACTION_TYPE: 4,
		ASSET_REISSUE_TRANSACTION_TYPE: 5,
		ASSET_BURN_TRANSACTION_TYPE: 6,
		EXCHANGE_TRANSACTION_TYPE: 7,
		START_LEASING_TRANSACTION_TYPE: 8,
		CANCEL_LEASING_TRANSACTION_TYPE: 9,
		CREATE_ALIAS_TRANSACTION_TYPE: 10,
		MASS_PAYMENT_TRANSACTION_TYPE: 11
	}
})();

// TODO: Change to Constants.IS_MIR
function isMir() {
	return Constants.IS_MIR;
}
